[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"
[functions]
  included_files = ["dist/**"]

[dev]
  command = "npm run dev"
  port = 25809
  targetPort = 25809

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/v1/:splat"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/api/docs"
  status = 200

[[redirects]]
  from = "/openapi.json"
  to = "/.netlify/functions/api/openapi.json"
  status = 200
